### ISSUE TITLE
The asciidoc.org redirect troubles

### ISSUE THREAD

**Issue by podsvirov** [asciidoc-py/asciidoc-py.github.io#2]
For example the page https://asciidoc.org/source-highlight-filter.html not found, but it should be route to page https://asciidoc-py.github.io/source-highlight-filter.html.

Can we directly change `website` attribute in `doc/asciidoc.txt` file?

**Comment by MasterOdin** [comment]
Fix would be similar to https://github.com/asciidoc-py/asciidoc-py/commit/ad2691525434ef0b95730beb21f0937a32cb9efd where need to make a new `html` file that has a redirect in the `gh-pages` branch of the main `asciidoc-py` repo.

It's definitely cumbersome, but purposely kept separate as at some point `asciidoc.org` will leave this org completely and be used for a more high level site as developed by the AsciiDoc Working Group.

**Comment by podsvirov** [comment]
It doesn't seem difficult. I'll try to fix it myself, if you don't mind?

**Comment by MasterOdin** [comment]
Go for it :+1:
